<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.49" />


<title>Lutosławski, “Principles of Stylometry&#34; (A Translation) - Silva Portentosa</title>
<meta property="og:title" content="Lutosławski, “Principles of Stylometry&#34; (A Translation) - Silva Portentosa">



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/SOMGP.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">



    <h1 class="article-title">Lutosławski, “Principles of Stylometry&#34; (A Translation)</h1>


    <div class="article-content">
      <p>Wincenty Lutosławski, “Principles of Stylometry Applied to the Chronology of Plato’s Works”<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
<p>[Translation of Wincenty Lutosławski, « Principes de stylométrie appliqués à la chronologie des œuvres de Platon », <em>Revue des Études Grecques</em> 11.41 (1898): 61–81.]</p>
<p>Translated by <a href="http://brianjreilly.com">Brian J. Reilly</a> [Original text is in the public domain in the United States of America; this translation is copyright © 2018 Brian J. Reilly; non-commercial use is allowed with attribution. Note that the status of this translation is preliminary! I have not polished it and may have made errors ranging from typos to downright mistranslations. Several of the Greek terms have not been checked from their OCR version, so caveat lector.]</p>
<p>[p. 61] In general, we do not need to fall back on the study of an author’s style to know the order in which they write their works.<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a> Most authors took care to indicate themselves the relation of each piece of writing to their previous writings, which allows us to take stock of their progress and the path they followed in arriving at their ultimate conclusions. Nevertheless, Plato handled each of his works with such perfect art and deigned so little to tell us about himself that it is rather difficult to find beginning or end of the admirable circle formed by his dialogues. From this is born the famous problem of Platonic chronology, believed unsolvable by many historians and handled in many contradictory ways by others. As we are dealing not only with an artist but a thinker, it is all the more important to know the order of Plato’s works than that of Shakespeare’s dramas, on which we have spent so much erudition and so many patient studies. We want to give an account of the development of form as well as thought when dealing with a philosopher who was also a great writer. The great difficulty consists in the almost complete absence of testimony [p. 62] about his life and his writings. We know only that <em>Laws</em> is a work of his late life, according to the testimony of Aristotle, and <em>Timaeus</em> and <em>Critias</em> are generally attributed to the same period. For no other work is there unanimity of opinion among experts. Even certain probabilities accepted by a large majority of Plato scholars — like the date of <em>Symposium</em> (c. 385 BCE) or the date of Crito as shortly after the death of Socrates — have been challenged by others.<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a> In this confusion of contrary opinions, only those studies based on the comparison of style and of vocabulary have lead researchers working independently from one another to mutually confirm their conclusions.</p>
<p>Up to now, two different methods have been proposed to determine the chronology of Plato’s dialogues through the study of their style. We can call these two methods by the nationalities of their inventors: the Scottish method and the German method.</p>
<p>The Scottish method had only one representative in the person of Lewis Campbell,<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a> who originally conceived the idea thirty years ago to compare the vocabulary of Plato’s dialogues by counting the number of rare words that each work had in common with the last three works: <em>Timaeus</em>; <em>Critias</em>; <em>Laws</em>. Campbell’s research, buried in the introduction of a special edition of the two dialogues, remained entirely unknown for twenty-eight years and were cited by no one, even though the commentary contained [p. 63] in the same volume was esteemed and cited by [Martin] Schanz and [David] Peipers. Campbell deserves credit for proving through his method that <em>Sophist</em>, <em>Statesman</em>, and <em>Philebus</em> belong to the same era as <em>Timaeus</em>, <em>Critias</em>, and <em>Laws</em> [TCL], which has been confirmed by all subsequent research on Plato’s style.<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a> But the Scottish method could only be applied to this latter group [TCL], the use of rare words being limited to these dialogues and to <em>Phaedrus</em>. Where there was no opportunity for the use of rare words, as in <em>Theaetetus</em> or <em>Parmenides</em>, the Scottish method could not give satisfactory results: These two dialogues appeared further removed from the group with <em>Laws</em> than <em>Symposium</em> or Phaedo, because the logically abstract content of <em>Theaetetus</em> and <em>Parmenides</em> did not lend itself to words deliberately created in the dialectical dialogues and maintained in the group with <em>Laws</em>. Thus, according to Campbell, <em>Philebus</em> contains 52 words which, outside of this dialogue, are found only in <em>Timaeus</em>, <em>Critias</em>, and <em>Laws</em> (including as well that also are found in <em>Sophist</em> and <em>Statesman</em>, for example: σύμ- μιξις, σχίζω, διαμερίζω, etc.). <em>Statesman</em> contains 75 words that join it to this latter group [TCL] (for example: άπο μερίζω, αποσχίζω, διαλαγχάνω, etc.); <em>Sophist</em>, 57 similar words<a href="#fn6" class="footnoteRef" id="fnref6"><sup>6</sup></a> (for example: διάγνωσης, συνεφέπομαι, etc.); <em>Republic</em>, 246 words; <em>Phaedrus</em>, 61 words. All the other dialogues have far fewer of those words characteristic of that latter group: For example, <em>Theaetetus</em> has only 27 and <em>Parmenides</em> 6. This inequality derived not only from the abstract content of these last two dialogues, but also from Campbell’s only counting words exclusively used in the last group [TCL] and in one of the preceding dialogues while omitting those that were common to several dialogues, for example, <em>Theaetetus</em>, [p. 64] <em>Parmenides</em>, and <em>Laws</em>. Unaware of Campbell, Dittenberger<a href="#fn7" class="footnoteRef" id="fnref7"><sup>7</sup></a> launched a new method in Germany in 1881 to compare the styles of Plato’s writings. He chose very frequent words whose use is limited to only a part of Plato’s works. For example, the interrogative TI MENE can only be found in nine dialogues (according to Dittenberger; later an isolated instance was also found in Lysis) where this formulation suddenly appears quite frequently: 35 times in <em>Republic</em>; 12 times in Phèdre; 13 times in <em>Theaetetus</em>; 6 times in <em>Parmenides</em>; 12 times in <em>Sophist</em>; 20 times in <em>Statesman</em>; 26 times in <em>Philebus</em>; and 48 times in <em>Laws</em>. Beyond these rather characteristic, very frequent words in a small number of dialogues but missing entirely from the rest, Dittenberger also studies the use of synonyms and he found that the prevalence of one synonym over another is rather striking in certain dialogues, for example καθάπερ is much more frequent than ώσπερ except in the six dialogues that, according to Campbell, are the latest, in which we also observe that the use of λέχριπερ replaces εωσπερ.</p>
<p>The German method had a great advantage over the Scottish method: It took account of much less accidental traits. Dittenberger had many successors<a href="#fn8" class="footnoteRef" id="fnref8"><sup>8</sup></a> in Germany and outside of Germany; one should add to it the work of M. Baron, recently published in this journal. But on the other hand, the number of stylistic traits observed by the Germans was far fewer than those collected by the Scottish scholars. The two methods have several shared weaknesses, which have up to now hindered many skilled researchers [p. 65] from accepting these studies in the “statistics of style” as being definitive. All of the statisticians of style have been seeking exclusive markers, limites to a small number of dialogues. They compared samples of text of unequal length, which offered more or fewer chances for the observed traits. They had not measured the text and supposed that the pages of the Estienne or Teubner editions were equal, although those pages contain a different number of words for different dialogues.<a href="#fn9" class="footnoteRef" id="fnref9"><sup>9</sup></a> But the main defect of all of studies of this type was the absence of a general theory, based on a foundational hypothesis clearly articulated and open to proof. It is the object of the present talk to propose such a theory and to state the foundational hypothesis of the new science of stylometry [stylométrie], or the measure of stylistics resemblances. To meet this goal, some definitions of terms are necessary:</p>
<ol style="list-style-type: decimal">
<li><p>A <em>styleme</em> [<em>stylème</em>] is any use of language that is not indispensable to express an idea [la pensée], i.e., which can be replaced by another. For example, the use of a rare word and especially of a word specially created with the goal of giving a more original inflection to the expression of the idea is a styleme, for such a word could in general have been replaced by a less rare word or by circumlocution. The frequency of each kind of word is also a styleme, even if the words whose frequency we calculate are indispensable. Thus πας and its derived [<em>composé</em>] words are used more than four times per page (Didot edition) only in the last six dialogues, being much rarer in all of Plato’s other works. Similarly, a frequency of 21 prepositions per page (Didot edition) is limited to <em>Phaedrus</em>, <em>Statesman</em>, <em>Timaeus</em>, <em>Critias</em>, and <em>Laws</em>. The use of prepositions is indispensable, but their unique frequency is not and constitutes a styleme. Similarly, the prevalence of one synonym over another, the position of [p. 66] a word in its sentence, the proportion of parts of speech are likewise stylemes.</p></li>
<li><p>The stylistic <em>resemblance</em> [<em>affinité stylistique</em>] of two texts depends on the number of stylemes that they have in common and on their importance, without however being proportional to the number of these stylemes. If we have three samples of text of equal length, A, B, C, and if we find in B 100 stylemes that are found in C, while A only has 50 stylemes in common with C, we would not be allowed to say that the stylistic resemblance of B to C is twice that of A to C. We would only know that B is closer to C than A is.</p></li>
<li><p>The <em>measure</em> of stylistic resemblance must take into account the different importance of stylemes. To this end, we take as the <em>unit</em> of resemblance the shared use in two different works of a styleme of the least important type, for example a rare word that is found only once in one dialogue and once in the other constitutes a unit of stylistic resemblance between the two works. As we observe new stylemes, we decide what degree of importance it would be proper to assign to them.</p></li>
</ol>
<p>Having defined the notions of styleme, of stylistic ressemblance, and of its measure, we proceed to articulating the principle that must serve as the basis of any comparison of style aiming to make conclusions about chronology. It is the following <em>law of stylometry</em>:</p>
<blockquote>
<p><em>From two samples of text of the same length compared to a third in terms of style, the one that presents a decidedly larger stylistic ressemblance given the standard of comparison will be closer to it in terms of its date of composition, so long as a sufficient number of stylemes has been studied and included in the calculation of ressemblances.</em></p>
</blockquote>
<p>A few terms of this law require a more precise determination. The number of stylemes studies, in order to be sufficient, must always go beyond a few hundred. It is only with large numbers that we arrive at the stability of stylometric equivalencies, such that the samples of text of equal [p. 67] length will contain the same quantity of them if they belong to the same era. The comparison of samples of equal length informs us about the limits of valid conclusions. Thus, for example, out of 500 stylemes in Plato<a href="#fn10" class="footnoteRef" id="fnref10"><sup>10</sup></a> observed in the last six dialogues (<em>Sophist</em>, <em>Statesman</em>, <em>Philebus</em>, <em>Timaeus</em>, <em>Critias</em>, <em>Laws</em>), we find close to the same number in samples of equal text in <em>Republic</em> and <em>Phaedrus</em> (which has generally been recognized as contemporaneous to <em>Republic</em>), namely:</p>
<ul>
<li>101 stylemes equivalent to 192 units in <em>Republic</em>, 412b–471c (39 pp., ed. Didot; 63 pp., ed. Teubner).</li>
<li>99 stylemes equivalent to 184 units in <em>Republic</em>, 543a–592b (34 pp., ed. Didot; 55 pp., ed. Teubner).</li>
<li>119 stylemes equivalent to 220 units in <em>Phaedrus</em>, 227a–279c (39 pp., ed. Didot ; 68 pp., ed. Teubner).</li>
</ul>
<p>Taking longer samples, the differences diminish. We find:</p>
<ul>
<li>111 stylemes equivalent to 211 units in <em>Republic</em>, 368a–445e (53 pp., ed. Didot ; 87 pp., ed. Teubner).</li>
<li>124 stylemes equivalent to 233 units in <em>Republic</em>, 543a–621d (53 pp., ed. Didot ; 86 pp., ed. Teubner).</li>
<li>130 stylemes equivalent to 233 units in <em>Theaetetus</em>, 142a–210d (33 pp., ed. Didot ; 68 pp., ed. Teubner).</li>
</ul>
<p>We see that three samples of texts, of which two are taken from the same work and a third from a work whose style is closely clustered with it (<em>Phaedrus</em> and <em>Theaetetus</em> have been recognized at the closest dialogues to <em>Republic</em> by all those who have studied Plato’s style), show almost the same resemblance with the last group of six dialogues, which proves that 500 stylemes are sufficient for conclusions about chronology, [p. 68] which amounts to samples of 34–53 pages in the Didot edition. At the same time, this example shows that the measure of text we use to measure the length of a sample is not unimportant. The last three samples, which are of equal length in the Didot edition, are 68–87 pages in the Teubner edition and 68–78 pages in the Estienne edition. If we compare these editions by counting the number of words on each page for different works, we shall find out that the pages of the Didot edition are much more equal between each other than are those in the other editions. This observation is very important, for all of our predecessors have made use of the pages of the Teubner or Estienne editions as the measure of text without noticing that these pages contain more or fewer words in different dialogues. In certain cases, this negligence prevented some interesting conclusions. Thus Lina,<a href="#fn11" class="footnoteRef" id="fnref11"><sup>11</sup></a> having studied the use of prepositions in all of Plato’s works, found no difference in frequency between dialogues so different in every respect as <em>Laches</em>, <em>Protagoras</em>, and <em>Statesman</em>, which, according to Lina, have the same frequency of 11 prepositions per page (Teubner edition). In reality, if the text is measured by pages in the Didot edition, 17 prepositions are found per page in <em>Protagoras</em>, 19.5 prepositions per page in <em>Laches</em>, and 21 prepositions per page in <em>Statesman</em>, a considerable difference that Lina did not notice and that confirms what we know moreover about the style of these dialogues. Taking care to only compare equal samples, we easily find the limits to the validity of our stylometric law for each number of compared stylemes. If we observe at 500 stylemes that texts belonging to the same period show an almost equal resemblance with a given standard, we can also easily convince ourselves that all cases where the relative order of two dialogues [p. 69] or of two parts of just one dialogue is known, the one that was written later has a greater resemblance to the last group. The following examples demonstrate this clearly:</p>
<ol style="list-style-type: upper-roman">
<li>The first book of <em>Republic</em> contains 28 accidental stylemes (each equivalent to 1 unit of resemblance), 6 repeated stylemes (each equivalent to 2 units), and 3 important stylemes (each equivalent to 3 units) that are found in the last group (<em>Sophist</em>, <em>Statesman</em>, <em>Philebus</em>, <em>Timaeus</em>, <em>Critias</em>, and <em>Laws</em>). This represents 49 units of resemblance. The tenth book of Republic contains 33 accidental stylemes, 14 repeated stylemes, 15 important stylemes, and 6 very important stylemes (each equivalent to 4 units), together equivalent to 132 units of resemblance. This relation is expressed in the following abbreviated manner:</li>
</ol>
<blockquote>
<blockquote>
<em>Republic</em> I (20.5 pages): 28<sup>I</sup> 6<sup>II</sup> 3<sup>III</sup> (= 49<sup>I</sup>)<br />
→ <em>Republic</em> X (19.5 pages): 35<sup>I</sup> 14<sup>II</sup> 15<sup>III</sup> 6<sup>IV</sup> (= 132<sup>I</sup>).<br />

</blockquote>
</blockquote>
<ol start="2" style="list-style-type: upper-roman">
<li>Books VIII–X of <em>Republic</em>, later than books II–IV, chronologically precede <em>Timaeus</em>, which constitutes their continuation. In agreement with this known fact, we find the resemblance of books VIII–X of <em>Republic</em> with the group of Laws well above that of books II–IV and less than that of Timaeus, the three samples being of equal length:</li>
</ol>
<blockquote>
<blockquote>
<p><em>Republic</em> II 368a–IV445e (53 pages): 47<sup>I</sup> 30<sup>II</sup> 32<sup>III</sup> 2<sup>IV</sup> (= 211<sup>I</sup>)<br />
→ <em>Republic</em> VIII–X (53.5 pages): 54<sup>I</sup> 36<sup>II</sup> 29<sup>III</sup> 5<sup>IV</sup> (= 233<sup>I</sup>)<br />
→ <em>Timaeus</em> (53 pages): 123<sup>I</sup> 58<sup>II</sup> 44<sup>III</sup> 14<sup>IV</sup> (= 427<sup>I</sup>).</p>
</blockquote>
</blockquote>
<ol start="3" style="list-style-type: upper-roman">
<li>Books II–IV of <em>Republic</em> are later than <em>Gorgias</em>, according to the opinion of the majority of authors able to judge, and they precede without doubt books V–VII, which continue them. The resemblance of these three samples with the group of <em>Laws</em> is expressed in the following formula: [p.70]</li>
</ol>
<blockquote>
<blockquote>
<p><em>Gorgias</em> (60 pages): 31<sup>I</sup> 20<sup>II</sup> 6<sup>III</sup> (= 89<sup>I</sup>)<br />
→<em>Republic</em> II–IV (60.5 pages): 47<sup>I</sup> 37<sup>II</sup> 32<sup>III</sup> 2<sup>IV</sup> (= 225<sup>I</sup>)<br />
→<em>Republic</em> V–VII (60 pages): 56<sup>I</sup> 29<sup>II</sup> 40<sup>III</sup> 7<sup>IV</sup> (= 262<sup>I</sup>).</p>
</blockquote>
</blockquote>
<ol start="4" style="list-style-type: upper-roman">
<li><em>Sophist</em>, being the continuation of <em>Theaetetus</em>, must have been written later and must have preceded <em>Statesman</em> according to Plato’s own indications. This is in accord with the following stylometric relation:</li>
</ol>
<blockquote>
<blockquote>
<p><em>Theaetetus</em> (53 pages): 58<sup>I</sup> 41<sup>II</sup> 31<sup>III</sup> (= 233<sup>I</sup>)<br />
→<em>Sophist</em> (40 pages): 139<sup>I</sup> 36<sup>II</sup> 59<sup>III</sup> 20<sup>IV</sup> (= 468<sup>I</sup>)<br />
→<em>Statesman</em> (43 pages): 163<sup>I</sup> 43<sup>II</sup> 56<sup>III</sup> 19<sup>IV</sup> (= 493<sup>I</sup>).</p>
</blockquote>
</blockquote>
<p>We see in all of these comparisons, which we could multiply indefinitely,<a href="#fn12" class="footnoteRef" id="fnref12"><sup>12</sup></a> that each time that we know one text comes after another, we find in it more stylemes proper to the <em>Laws</em> group, recognized as the standard of Plato’s late style. Thus the validity of the law of stylometry has been demonstrated within the limits of 300 stylemes applied to samples of 40 or more pages (Didot edition).</p>
<p>To take account of the significance of this result, it should be known that the 300 stylemes serving as the basis for our comparisons were chosen without the least bias in favor of any chronological order of the dialogues and that they represent the entirety of 58,000 observations made by twenty different authors on Plato’s style over the last sixty years. It is thus a summary result of half a century of observations. The authors from whom we have taken our materials did not imagine the application that could be done with them and in no way dreamed of classifying the observed stylemes according to their relative importance with the aim of comparing their equivalencies of resemblance. The classification [p. 71] that served to establish the comparisons above distinguishes four degrees of importance for the observed stylemes:</p>
<ol style="list-style-type: upper-roman">
<li><p><em>Accidental</em> stylemes are words or phrases separate from the content only found once in the dialogue. This class is the most numerous: It includes rarely used words like έξισοῦµαι (<em>Republic</em>, <em>Parmenides</em>, <em>Laws</em>), ἀπίθανος (<em>Phaedrus</em>, <em>Parmenides</em>, <em>Laws</em>), παντοδαπῶɩ (<em>Parmenides</em>, <em>Laws</em>), άγράριριατος (<em>Statesman</em>, <em>Timaeus</em>, <em>Critias</em>); these words are not indispensable in the passages where we find them and could have easily been replaced by other words. Here belong as well certain rare uses or combinations of common words, for example ἤδη τοίνυν, which is only found once in <em>Laws</em> and likewise once in several other dialogues (<em>Meno</em>, <em>Cratylus</em>, <em>Statesman</em>, <em>Philebus</em>), πάντως καὶ πάντῃ (<em>Republic</em>, once; <em>Philebus</em>, once), πᾶς όστισοῦν (<em>Statesman</em>, once; <em>Philebus</em>, once; <em>Laws</em>, once), περί separated from its genitive by μὲν γάρ (<em>Republic</em>, once; <em>Theaetetus</em>, once; <em>Statesman</em>, once), κατὰ τὸ ὀρθόν (<em>Sophist</em>, once; <em>Timaeus</em>, once; <em>Laws</em>, once), ὄμοιον χατά τινα (<em>Phaedrus</em>, once; <em>Statesman</em>, once; <em>Timaeus</em>, once; <em>Laws</em>, once). Similar coincidences between two or more dialogues has, of course, no importance is they are considered separately, but when we observe that two works A and B have many more coincidences between them than A and C, we have the right to conclude that there is a greater stylistic resemblance between A and B than between A and C, especially if this resemblance is confirmed by stylemes of greater importance, as always happens. Thus every coincidence of accidental stylemes between two dialogues or between a dialogue and a group of dialogues can be estimated as one unit of resemblance.</p></li>
<li><p><em>Repeated</em> stylemes are those that are found more than once in a dialogue without becoming frequent. For example, µέθεξις (<em>Parmenides</em>, 3 times; <em>Sophist</em>, 3 times), τάχα ἴσως (<em>Sophist</em>, 2 times; <em>Statesman</em> and <em>Philebus</em>, 3 times; <em>Timaeus</em>, once; <em>Laws</em>, 11 times), τοιγαροῦν (<em>Sophist</em>, 3 times; <em>Laws</em>, 2 times), πρέπον ἂν εἴη (<em>Timaeus</em>, 2 times; <em>Laws</em>, 16 times). These stylemes have been estimated as equivalent to two units of resemblance when they are common between one dialogue and another. Here belong as well [p. 72] certain degrees of frequency of common words, for example πᾶς and its compounds, more than once in three pages and less than once in two pages; a frequency of prepositions of 16.5–19 per page; πέρι placed after the genitive making up 6–10 per 100 of the total number of περί, etc.</p></li>
<li><p><em>Important</em> stylemes are those that, being frequent in certain dialogues, are absent in others. We call a word frequent if it is found more than once in 12 pages, without being a common word and indispensable to the expression of the idea. For these latter, the degree of frequency qualifying as an important styleme must be estimated separately for each case. Thus we have included in this class πᾶς and its compounds more than four times on one page (only: <em>Sophist</em>, <em>Statesman</em>, <em>Philebus</em>, <em>Timaeus</em>, <em>Critias</em>, <em>Laws</em>), a frequency of prepositions exceeding 19 per page, πέρι after the genitive making up 10–20 per 100 of all uses of περί, a prevalence of χαθάπερ over ὥσπερ, of χαὶ µήν over ἀλλὰ µήν, of τοίνυν over µέντοι, of εἶπον over ἔλεγον, of πάνυ µὲν οὖν over πάνυγε, of ξύµπας over ἅπας, etc. Each important styleme has been estimated as equivalent to three units of resemblance.</p></li>
<li><p><em>Very important</em> stylemes are words that are very frequent (more than once in two pages) without being indispensable, as well as certain degrees of frequency of common words, for example πᾶς and its compounds more than five times per page (only: <em>Statesman</em>, <em>Timaeus</em>, <em>Critias</em>, <em>Laws</em>), µέντοι less than once in five pages (only: <em>Statesman</em>, <em>Philebus</em>, <em>Timaeus</em>, <em>Critias</em>), ἅπας, ξύμπας, ξυνάπας more than once per page (only: <em>Statesman</em>, <em>Timaeus</em>, <em>Critias</em>, <em>Laws</em>), a frequency of prepositions beyond 21 times per page (only: <em>Phaedrus</em>, <em>Statesman</em>, <em>Timaeus</em>, <em>Critias</em>, <em>Laws</em>), πέρι after the genitive making up more than 20 per 100 of all uses of περί, interrogatives using ἆρɑ making up 24 percent of all interrogatives, etc. Each styleme of this class has been estimated as equivalent to four units.<a href="#fn13" class="footnoteRef" id="fnref13"><sup>13</sup></a></p></li>
</ol>
<p>[p. 73]</p>
<div class="figure">
<img src="/files/Lutoslawski.Principes.74.png" title="Table of Resemblances" alt="Table of Resemblances of the Principle Dialogues with the Group of Laws Based on a Comparison of 500 Stylemes" />
<p class="caption">Table of Resemblances of the Principle Dialogues with the Group of <em>Laws</em> Based on a Comparison of 500 Stylemes</p>
</div>
<pre class="r"><code>(table.p74.df &lt;- read.csv(file = &quot;https://raw.githubusercontent.com/BJPR/website-hugo/master/public/files/Lutoslawski.Principes.74.csv&quot;))</code></pre>
<pre><code>##    Dialogue_Name Didot_Pages Stelemes_Accidental Stylemes_Repeated
## 1        Apology          20                   9                 2
## 2      Euthyphro          12                  11                 2
## 3          Crito          10                  13                NA
## 4      Charmides          18                  13                 5
## 5         Laches          18                  19                 4
## 6     Protagoras          40                  21                 9
## 7           Meno          23                  20                16
## 8     Euthydemus          28                  22                 5
## 9        Gorgias          62                  31                20
## 10      Cratylus          42                  33                16
## 11     Symposium          39                  42                16
## 12        Phaedo          49                  43                26
## 13    Republic 1          20                  28                 6
## 14 Republic 2to4          60                  47                37
## 15 Republic 5to7          60                  56                29
## 16 Republic 8to9          34                  47                22
## 17   Republic 10          19                  35                14
## 18      Phaedrus          39                  54                36
## 19    Theaetetus          53                  58                41
## 20    Parmenides          31                  56                42
## 21       Sophist          40                 139                36
## 22     Statesman          43                 163                43
## 23      Philebus          43                 100                38
## 24       Timaeus          53                 123                58
## 25       Critias          11                  51                 8
## 26          Laws         236                 175               176
##    Stylemes_Important Stylemes_Laws Units Relative_Resemblance
## 1                   1            NA    16                 0.02
## 2                   1            NA    18                 0.03
## 3                   5            NA    28                 0.04
## 4                   6            NA    41                 0.06
## 5                   8            NA    51                 0.07
## 6                   4            NA    51                 0.07
## 7                   3            NA    61                 0.08
## 8                   7            NA    53                 0.08
## 9                   6            NA    89                 0.12
## 10                 15             1   114                 0.16
## 11                  8            NA    98                 0.14
## 12                 17             2   154                 0.21
## 13                  3            NA    49                 0.07
## 14                 32             2   225                 0.31
## 15                 40             7   262                 0.36
## 16                 27             3   184                 0.26
## 17                 15             6   132                 0.18
## 18                 22             7   220                 0.31
## 19                 31            NA   233                 0.32
## 20                 21            10   243                 0.34
## 21                 59            20   468                 0.65
## 22                 56            19   493                 0.69
## 23                 55            16   405                 0.56
## 24                 44            14   427                 0.60
## 25                 18            12   169                 0.24
## 26                 37            20   718                 1.00</code></pre>
<p>[p. 75]</p>
<p>In comparing the numbers of this table, we must always remember that only equal length samples of text are are comparable. Thus, for example, because <em>Cratylus</em> is much longer than <em>Symposium</em>, we cannot conclude from its greater resemblance to the last group that it was written later, even more so as the difference is insignificant. One of the most frequent errors, recently committed by Eduard Zeller<a href="#fn14" class="footnoteRef" id="fnref14"><sup>14</sup></a>, is to believe that the number of stylemes observed in some sample of text is proportional to the length of the sample. If one compares samples of contiguous text of unequal length, it can clear be seen to be otherwise. So, for example, we find over 7.5 pages of book 2 of <em>Republic</em> (357a–367e) only 21 units of resemblance with the last group, whereas the next 29 pages (368a–412a) have 150 units, or 7 times more in a text only 4 times longer. In another instance, the difference is much smaller, with a text 3 times longer than another (471c–541b compared to 449a–471b) having less than double the number of units of resemblance with the last group (234 to 122).</p>
<p>One could cite many more similar examples that prove that only samples of equal length are comparable. This principle has not been able to be applied with all the necessary precision up to now because our predecessors treated each dialogue as a whole and did not always enumerate the passages, which does not allow a calculation of the number of stylemes found in equal samples. But in the future all stylometric studies should be based on the division of all of Plato’s text into equal samples, for example of ten pages each (Didot edition). [p.76] We observe that the style of the first book of <em>Republic</em> is extremely far removed from the last group, which proves that the later corrections and additions do not essentially alter the stylometric character of a text. For there is no doubt that the first book of <em>Republic</em> was reworked and revisited when Plato wrote its continuation, for as it is, it forms an inseparable whole with the following books. Thus we do not accept second-edition hypotheses as an explanation for great differences in style: It has often been affirmed that our text for <em>Phaedrus</em> and for <em>Theaetetus</em> were revised and corrected second editions and that these revisions explained the great resemblance of style between these two dialogues and the last group. If a revision can thus alter style, the first book of <em>Republic</em> should have been thus affected and would not have been able to remain so far removed from the from the books that followed in terms of style.</p>
<p>The certain conclusions that result from our our table of resemblances are as follows:</p>
<ol style="list-style-type: decimal">
<li><p>Plato’s last works are <em>Sophist</em>, <em>Statesman</em>, <em>Philebus</em>, <em>Timaeus</em>, <em>Critias</em>, and <em>Laws</em>, which a relative resemblance in excess of .5 for samples of 40 pages. This means that, over some sufficient quantity of observed stylemes in Plato’s works, each of his [<em>sic</em>; read: <em>these</em>?] dialogues will contain more than half the number found in <em>Laws</em>. Since <em>Critias</em> is only 11 pages, the 29 preceding pages from <em>Timaeus</em> have to be added to them for the comparisons.</p></li>
<li><p>The last group is preceded by <em>Republic</em>, <em>Phaedrus</em>, <em>Theaetetus</em>, and <em>Parmenides</em>, which have a relative resemblance less than .4 for samples of 30–60 pages.</p></li>
<li><p>An even earlier group comprises <em>Cratylus</em>, <em>Symposium</em>, and <em>Phaedo</em>, for which the relative resemblance is lowered to .2 and less.</p></li>
<li><p><em>Gorgias</em> preceded these dialogues, being later than all Socratic dialogues.</p></li>
</ol>
<p>To go beyond these conclusions and establish the chronological order [p. 77] of the Socratic dialogues, more numerous observations relating to new stylemes would be needed. A reinvestigation of the known stylemes while maintaining the principle of comparing exactly equal stylemes is also very desirable and could serve to demonstrate more precisely the order of the dialogues in each of the groups noted above. Lewis Campbell <a href="#fn15" class="footnoteRef" id="fnref15"><sup>15</sup></a> gathered more than 1000 rare words found in the dialogues preceding <em>Republic</em>, and the results of these new calculations confirm our conclusions rather remarkably, as we see in the following table:</p>
<div class="figure">
<img src="/files/Lutoslawski.Principes.77.png" title="Table of Coincidences" alt="Coincidences of the Use of 1000 Stylemes Observed by Lewis Campbell in the Dialogues Composed between Meno and Symposium" width="800" height="600" />
<p class="caption">Coincidences of the Use of 1000 Stylemes Observed by Lewis Campbell in the Dialogues Composed between <em>Meno</em> and <em>Symposium</em></p>
</div>
<p>Here, only the numbers in the vertical columns are comparable, and we should not expect to find a perfect agreement with the law of resemblance, for this law applies to texts of equal length, while the dialogues compared are of unequal length. Nevertheless, we see that the resemblance of each dialogue to those that followed is greater [p. 78] the closer it is to them. Thus <em>Euthydemus</em> has almost the same number of stylemes in common with <em>Symposium</em> as does <em>Meno</em>, but if we compare the two dialogues with a better standards, we see every time that <em>Euthydemus</em> seems later than <em>Meno</em>, <em>Gorgias</em> later than <em>Euthydemus</em>. The two exceptions that we see are insignificant and can be easily explained. <em>Cratylus</em>, written after <em>Gorgias</em>, only has 56 stylemes in common with <em>Symposium</em>, whereas <em>Gorgias</em> has 63. But <em>Gorgias</em> is one and a half times longer than <em>Cratylus</em>, and had we compared a part if <em>Gorgias</em> equal in length to <em>Cratylus</em> we would certainly have found the resemblance of <em>Cratylus</em> to <em>Symposium</em> greater than that of <em>Gorgias</em>. For the same reason <em>Gorgias</em> has more stylemes than <em>Cratylus</em> in common with <em>Republic</em> and <em>Phaedrus</em>. But other than these two anomalies, we find the results of our resemblance table confirmed by the new calculations by Campbell. The order of Plato’s dialogues from <em>Meno</em> on is beyond doubt<a href="#fn16" class="footnoteRef" id="fnref16"><sup>16</sup></a> in terms of the primary groups. <em>Meno</em>, written after <em>Protagoras</em> and the short Socratic dialogues, is the first of Plato’s works where he boldly goes beyond the teachings of his master. After <em>Meno</em>, Plato wrote <em>Euthydemus</em> and <em>Gorgias</em>, which seem to have prepared the founding of the Academy. The first years of this association’s existence produced <em>Cratylus</em>, <em>Symposium</em>, and <em>Phaedo</em>, texts in which the theory of Ideas appears for the first time. Then Plato worked (around 384–379) on <em>Republic</em> and <em>Phaedrus</em>. After this latter dialogue, from the difference in style and doctrine between <em>Phaedo</em> and <em>Theaetetus</em> it is probably that there was a long interruption in his activity. <em>Theaetetus</em>, together with <em>Parmenides</em>, introduced a reform in Plato’s logic and metaphysics by substituting categories for the Ideas and [p. 79] by identifying qualitative alteration with mouvement in space. The new program of dialectical investigations, sketched out in <em>Parmenides</em>, is executed in <em>Sophist</em>, <em>Statesman</em>, and <em>Philebus</em>. Finally, Plato, noticing that the majority of his students were incapable of rising to level of these metaphysical discussions and perhaps himself feeling fatigued with the effort these discussions required, employed the last years of his old age in giving us in <em>Timaeus</em> his fables on the creation of the world and in <em>Laws</em> his opinions on a government realizable amidst human imperfection and on the religious beliefs that could contribute to maintain it and that agree with the metaphysical conclusions previously obtained.</p>
<p>Such is the image of Plato’s development given by the minute study of his style. There remains a lot to do to set out the details. Thus the order of the short Socratic dialogues is uncertain and the chronological relation between <em>Cratylus</em> and <em>Symposium</em>, between <em>Phaedrus</em> and the different parts of <em>Republic</em>, between <em>Philebus</em> and <em>Statesman</em>, between <em>Timaeus</em> and <em>Laws</em>, is debatable.</p>
<p>To find the definitive solution to these secondary problems, it would be necessary to apply the principles of stylometry with greater rigor than the imperfection of current observations have to now permitted. First, we would divide Plato’s works into samples of equal length text, measuring length by pages in the Didot edition, or even better by words! Thus five thousand words would be a sample of text sufficient for us to be able to observe the principle stylemes proper to the era of its composition. A more limited number of truly important stylemes would be a much stronger tool for research than a large number of accidental stylemes, but nothing should be neglected in order to have the most complete image of the style of each dialogue, and it would always be necessary to add newly observed stylemes to those indicated above. Thus no subsequent study of Plato’s style [p. 80] should be based on a number of stylemes fewer than 500. The stylometric method is obviously applicable to other texts and other authors. Let’s suppose that we have a series of works by the same author, A, B, C, D, E, etc., of unknown date to be determined by a study of their style. We begin by dividing each work into text samples of 5,000 works, which we designate as A<sub>1</sub>, A<sub>2</sub>, A<sub>3</sub>, etc, and we count the number of times each styleme is found in each sample, while establishing their degrees of importance in terms of the frequency of the stylemes. A large number of these degrees complicates the calculations and, in general, we accept 4 to 5 degrees equivalent to as many units of affinity.</p>
<p>The observations form a list in which the presence or absence and the importance of each styleme in each sample will be noted. To ensure that the observations have reached a sufficient number, the number of stylemes observed in contiguous samples clearly belonging to the same era, for example A<sub>1</sub>, A<sub>2</sub>, A<sub>3</sub>, B<sub>1</sub>, B<sub>2</sub>, B<sub>3</sub>, etc, must be compared. We shall find that these samples contain close to the same number of stylemes, and so we proceed to establish the order of the works by measuring the stylistic affinity of each to a given standard. As a standard, we take the work with the largest dimensions. Even when we know nothing at all about the order of the works, and when we do not even have an indication (as we do have for Plato) which is the last work, a simple calculation allows us to establish the sequence of the given works. Suppose, for example, that as the result of an investigation of 500 stylemes in five works, A, B, C, D, and E, we find that A contains 200 stylemes in common with C, B contains 300, D contains 300, and E contains 200. We will know first that B and D are closer to C than are A and E. And if we further find that B has more affinity with A than C and D, and that C has more affinity with D than A and B, the result of the works can only be: A, B, C, D, E or E, D, C, B, A. To decide between these two possible orders, stylometry alone will not suffice, and one would have to compare the content [p. 81] of the works or even look for indications of another kind. But, in most cases, similar indications exist, and moreover works written later by Plato as by other great writers have a greater variety and a greater stylistic richness, which is to say a greater number of stylemes. We see that stylometry of the Polish Method offers an infinitely more fertile ground than the Scottish or German statistics of style used up till now and permits an increase in the certainly of our conclusions through ever newer conclusions.</p>
<p>We have established the order of Plato’s dialogues by measuring their stylistic affinity with the latest group with <em>Laws</em>. This order will be confirmed by measuring the affinity of each work with <em>Republic</em> or <em>Gorgias</em>, or any group of dialogues whatsoever.</p>
<p>These comparisons will confirm as well the law of affinities which is all the more precisely applicable the more numerous and the more characteristic the observed stylemes are. This leads us to a new science of stylometry, which is a powerful supplemental tool for literary history and for the history of human thought.</p>
<div style="text-align: right">
W. Lutoslawski
</div>
<p><img src="/post/2018-10-06-principles-of-stylometry_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Summary of a talk given to the <em>Académie des Inscriptions et Belles-Lettres</em> at the 18 June 1897 session. [TR: It was a Friday.]<a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>TR: I use they as a third-person singular pronoun.<a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>For evidence for this claim, see pp. 35–63, 241, 351–357, and 386–391 of W. Lutoslawski, <em><a href="https://archive.org/details/origingrowthofpl00lutoiala/">The Origin and Growth of Plato’s Logic</a></em>, London, 1897.<a href="#fnref3">↩</a></p></li>
<li id="fn4"><p><em>The Sophistes and Politicus of Plato, with a revised text and English notes</em> by the Rev. Lewis Campbell, Oxford, 1867. The importance of this work as containing a new method to study Plato’s style was first recognized in Poland in a work published in the <em>Mémoires de l’Académie des sciences de Cracovie</em>, vol. XXVI, p. 31-195 : “Ο pierwszych trzech tetralogiach dziel Platona,” which was summarized in <em>Archiv fur Geschichte der Philosophie</em>, vol. IX, pp. 67-114 (October 1895) : <em>Ueber Echtheit Reihenfolge und logische Theorien von Plato’s drei ersten Tetralogien</em> and in the <em>Bulletin de l’Académie des sciences de Cracovie</em> October 1895, pp. 268–277.<a href="#fnref4">↩</a></p></li>
<li id="fn5"><p>See pp. 416–471 of W. Lutoslawski, <em>The Origin and Growth of Plato’s Logic</em>. For sake of brevity, this work will be cited below as <em>Plato’s Logic</em>.<a href="#fnref5">↩</a></p></li>
<li id="fn6"><p>For the enumeration and classification of these words, see pp. 88–99 of <em>Plato’s Logic</em>.<a href="#fnref6">↩</a></p></li>
<li id="fn7"><p>Dittenberger, <em>Sprachliche Kriterien fur die Chronologie der platonischen Dialoge</em>, in <em>Hermes</em>, vol. XV, p. 321. Berlin, 1881.<a href="#fnref7">↩</a></p></li>
<li id="fn8"><p>An analysis of the most important studies of this kind can be found in the essay <em>Sur une nouvelle méthode pour déterminer la chronologie des dialogues de Platon</em>, read on 16 May 1896 [TR: a Saturday] to the <em>Académie des sciences morales</em> [<em>et politiques</em>] and published in vol. CXLVI, n° 7 of the <em>Compte rendu</em> of this academy [<a href="https://gallica.bnf.fr/ark:/12148/bpt6k2992435/f960.item">pp. 114–33; responses 133–35</a>]. Forty-five publications of Plato’s style are summarized in <em>Plato’s Logic</em>, pp. 74–140.<a href="#fnref8">↩</a></p></li>
<li id="fn9"><p>See pp. 130 and 141 of <em>Plato’s Logic</em>.<a href="#fnref9">↩</a></p></li>
<li id="fn10"><p>The enumeration and discussion of these 500 stylemes gathered by twenty different authors at pp. 76–79, 85–88, 93–97, 100–104, 106–111, 115–133, and 137–139 of <em>Plato’s Logic</em>, and at pp 176–198 of vol. CX of the <em>Zeitschrift für Philosophie und philosophische Kritik</em>, in the September 1897 installment. See also the article <a href="https://books.google.com/books?id=itJMAAAAMAAJ&amp;q=Stylometrisches&amp;dq=Stylometrisches&amp;hl=en&amp;sa=X&amp;ved=0ahUKEwiK06KD2ZbeAhXpYt8KHcKfAJEQ6AEINzAC">“Stylometrisches”</a> in the CXIIth volume of the same <em>Zeitschrift</em>.<a href="#fnref10">↩</a></p></li>
<li id="fn11"><p>T. Lina, <em>De praepositionum usu platonico</em>. Marpurgi, 1889. The numbers given by Lina for the frequency of the use of πέρι following the genitive are in disagreement with those given by M. Baron.<a href="#fnref11">↩</a></p></li>
<li id="fn12"><p>A great number of similar comparisons are found in <em>Plato’s Logic</em> and also in the article <a href="https://www.jstor.org/stable/691558">“On Stylometry”</a> (<em>Classical Review</em>, vol. XI, pp. 284–86, July 1897).<a href="#fnref12">↩</a></p></li>
<li id="fn13"><p>For the complete list, see pp. 146–51 of <em>Plato’s Logic</em> and pp. 202–4 of vol. CX of <em>Zeitschrift für Philosophie</em> (September 1897).<a href="#fnref13">↩</a></p></li>
<li id="fn14"><p>See <em>Archiv für Geschichte der Philosophie</em>, vol. X, pp. 592–95, where Zeller, having found in about a sixth of [Friedrich] Ast’s dictionary <a href="https://archive.org/details/lexiconplatonicu03astfuoft">[<em>Lexicon Platonicum</em>]</a> a certain number of words of each dialogue shared with <em>Republic</em> and <em>Laws</em>, draws entirely false conclusions about their frequency per page and thinks he has proved the uncertainty of the Scottish method of the statistics of style because, in a sixth of Ast’s dictionary, he found a dozen of words common to <em>Phaedrus</em> and to <em>Laws</em>, more words than are common to <em>Laws</em> and to <em>Sophist</em> or to <em>Philebus</em>.<a href="#fnref14">↩</a></p></li>
<li id="fn15"><p>The collection of observation is still unpublished, but will be published in <em>Classical Review</em>.<a href="#fnref15">↩</a></p></li>
<li id="fn16"><p>This order has, moreover, been confirmed as well by a large number of comparisons of doctrines and by other arguments at <em>Plato’s Logic</em>, pp. 194–218, 231–33, 240–44, 261–65, 341–57, 366–67, 385–400, etc.<a href="#fnref16">↩</a></p></li>
</ol>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="https://bookdown.org/yihui/blogdown/" class="footer-links-kudos">Made with blogdown <img src="/images/blogdown-logo.png" alt="Img link to blogdown website" width="22" height="22">
<p></p>
<a>&</a>
<p></p>
<a href="https://gohugo.io/" class="footer-links-kudos">with Hugo <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

