---
title: Lutosławski, “Principles of Stylometry"
author: Brian J. Reilly (translator)
date: '2018-10-06'
slug: principles-of-stylometry
categories: []
tags: []
---

Wincenty Lutosławski, “Principles of Stylometry Applied to the Chronology of Plato’s Works”[^1]

[Translation of Wincenty Lutosławski, « Principes de stylométrie appliqués à la chronologie des œuvres de Platon », *Revue des Études Grecques* 11.41 (1898): 61–81.]

Translated by [Brian J. Reilly](http://brianjreilly.com)
[Original text is in the public domain in the United States of America; this translation is copyright © 2018 Brian J. Reilly; non-commercial use is allowed with attribution. Note that the status of this translation is preliminary! I have not polished it and may have made errors ranging from typos to downright mistranslations. The Greek terms have not been checked from their OCR version, so caveat lector.]

[p. 61]
In general, we do not need to fall back on the study of an author’s style to know the order in which they write their works.[^2] Most authors took care to indicate themselves the relation of each piece of writing to their previous writings, which allows us to take stock of their progress and the path they followed in arriving at their ultimate conclusions. Nevertheless, Plato handled each of his works with such perfect art and deigned so little to tell us about himself that it is rather difficult to find beginning or end of the admirable circle formed by his dialogues. From this is born the famous problem of Platonic chronology, believed unsolvable by many historians and handled in many contradictory ways by others. As we are dealing not only with an artist but a thinker, it is all the more important to know the order of Plato’s works than that of Shakespeare’s dramas, on which we have spent so much erudition and so many patient studies. We want to give an account of the development of form as well as thought when dealing with a philosopher who was also a great writer. The great difficulty consists in the almost complete absence of testimony
[p. 62]
about his life and his writings. We know only that *Laws* is a work of his late life, according to the testimony of Aristotle, and *Timaeus* and *Critias* are generally attributed to the same period. For no other work is there unanimity of opinion among experts. Even certain probabilities accepted by a large majority of Plato scholars — like the date of *Symposium* (c. 385 BCE) or the date of Crito as shortly after the death of Socrates — have been challenged by others.[^3] In this confusion of contrary opinions, only those studies based on the comparison of style and of vocabulary have lead researchers working independently from one another to mutually confirm their conclusions.

Up to now, two different methods have been proposed to determine the chronology of Plato’s dialogues through the study of their style. We can call these two methods by the nationalities of their inventors: the Scottish method and the German method.

The Scottish method had only one representative in the person of Lewis Campbell,[^4] who originally conceived the idea thirty years ago to compare the vocabulary of Plato’s dialogues by counting the number of rare words that each work had in common with the last three works: *Timaeus*; *Critias*; *Laws*. Campbell’s research, buried in the introduction of a special edition of the two dialogues, remained entirely unknown for twenty-eight years and were cited by no one, even though the commentary contained [p. 63] in the same volume was esteemed and cited by [Martin] Schanz and [David] Peipers. Campbell deserves credit for proving through his method that *Sophist*, *Statesman*, and *Philebus* belong to the same era as *Timaeus*, *Critias*, and *Laws* [TCL], which has been confirmed by all subsequent research on Plato’s style.[^5] But the Scottish method could only be applied to this latter group [TCL], the use of rare words being limited to these dialogues and to *Phaedrus*. Where there was no opportunity for the use of rare words, as in *Theaetetus* or *Parmenides*, the Scottish method could not give satisfactory results: These two dialogues appeared further removed from the group with *Laws* than *Symposium* or Phaedo, because the logically abstract content of *Theaetetus* and *Parmenides* did not lend itself to words deliberately created in the dialectical dialogues and maintained in the group with *Laws*. Thus, according to Campbell, *Philebus* contains 52 words which, outside of this dialogue, are found only in *Timaeus*, *Critias*, and *Laws* (including as well that also are found in *Sophist* and *Statesman*, for example: σύμ- μιξις, σχίζω, διαμερίζω, etc.). *Statesman* contains 75 words that join it to this latter group [TCL] (for example: άπο μερίζω, αποσχίζω, διαλαγχάνω, etc.); *Sophist*, 57 similar words[^6] (for example: διάγνωσης, συνεφέπομαι, etc.); *Republic*, 246 words; *Phaedrus*, 61 words. All the other dialogues have far fewer of those words characteristic of that latter group: For example, *Theaetetus* has only 27 and *Parmenides* 6. This inequality derived not only from the abstract content of these last two dialogues, but also from Campbell’s only counting words exclusively used in the last group [TCL] and in one of the preceding dialogues while omitting those that were common to several dialogues, for example, *Theaetetus*, [p. 64] *Parmenides*, and *Laws*. Unaware of Campbell, Dittenberger[^7] launched a new method in Germany in 1881 to compare the styles of Plato’s writings. He chose very frequent words whose use is limited to only a part of Plato’s works. For example, the interrogative TI MENE can only be found in nine dialogues (according to Dittenberger; later an isolated instance was also found in Lysis) where this formulation suddenly appears quite frequently: 35 times in *Republic*; 12 times in Phèdre; 13 times in *Theaetetus*; 6 times in *Parmenides*; 12 times in *Sophist*; 20 times in *Statesman*; 26 times in *Philebus*; and 48 times in *Laws*. Beyond these rather characteristic, very frequent words in a small number of dialogues but missing entirely from the rest, Dittenberger also studies the use of synonyms and he found that the prevalence of one synonym over another is rather striking in certain dialogues, for example καθάπερ is much more frequent than ώσπερ except in the six dialogues that, according to Campbell, are the latest, in which we also observe that the use of λέχριπερ replaces εωσπερ.

The German method had a great advantage over the Scottish method: It took account of much less accidental traits. Dittenberger had many successors[^8] in Germany and outside of Germany; one should add to it the work of M. Baron, recently published in this journal. But on the other hand, the number of stylistic traits observed by the Germans was far fewer than those collected by the Scottish scholars. The two methods have several shared weaknesses, which have up to now hindered many skilled researchers [p. 65] from accepting these studies in the “statistics of style” as being definitive. All of the statisticians of style have been seeking exclusive markers, limites to a small number of dialogues. They compared samples of text of unequal length, which offered more or fewer chances for the observed traits. They had not measured the text and supposed that the pages of the Estienne or Teubner editions were equal, although those pages contain a different number of words for different dialogues.[^9] But the main defect of all of studies of this type was the absence of a general theory, based on a foundational hypothesis clearly articulated and open to proof. It is the object of the present talk to propose such a theory and to state the foundational hypothesis of the new science of stylometry [stylométrie], or the measure of stylistics resemblances. To meet this goal, some definitions of terms are necessary:

1. A *styleme* [*stylème*] is any use of language that is not indispensable to express an idea [la pensée], i.e., which can be replaced by another. For example, the use of a rare word and especially of a word specially created with the goal of giving a more original inflection to the expression of the idea is a styleme, for such a word could in general have been replaced by a less rare word or by circumlocution. The frequency of each kind of word is also a styleme, even if the words whose frequency we calculate are indispensable. Thus πας and its derived [*composé*] words are used more than four times per page (Didot edition) only in the last six dialogues, being much rarer in all of Plato’s other works. Similarly, a frequency of 21 prepositions per page (Didot edition) is limited to *Phaedrus*, *Statesman*, *Timaeus*, *Critias*, and *Laws*. The use of prepositions is indispensable, but their unique frequency is not and constitutes a styleme. Similarly, the prevalence of one synonym over another, the position of [p. 66] a word in its sentence, the proportion of parts of speech are likewise stylemes.

2. The stylistic *resemblance* [*affinité stylistique*] of two texts depends on the number of stylemes that they have in common and on their importance, without however being proportional to the number of these stylemes. If we have three samples of text of equal length, A, B, C, and if we find in B 100 stylemes that are found in C, while A only has 50 stylemes in common with C, we would not be allowed to say that the stylistic resemblance of B to C is twice that of A to C. We would only know that B is closer to C than A is.

3. The *measure* of stylistic resemblance must take into account the different importance of stylemes. To this end, we take as the *unit* of resemblance the shared use in two different works of a styleme of the least important type, for example a rare word that is found only once in one dialogue and once in the other constitutes a unit of stylistic resemblance between the two works. As we observe new stylemes, we decide what degree of importance it would be proper to assign to them.

Having defined the notions of styleme, of stylistic ressemblance, and of its measure, we proceed to articulating the principle that must serve as the basis of any comparison of style aiming to make conclusions about chronology. It is the following *law of stylometry*:

> *From two samples of text of the same length compared to a third in terms of style, the one that presents a decidedly larger stylistic ressemblance given the standard of comparison will be closer to it in terms of its date of composition, so long as a sufficient number of stylemes has been studied and included in the calculation of ressemblances.*

A few terms of this law require a more precise determination. The number of stylemes studies, in order to be sufficient, must always go beyond a few hundred. It is only with large numbers that we arrive at the stability of stylometric equivalencies, such that the samples of text of equal [p. 67] length will contain the same quantity of them if they belong to the same era. The comparison of samples of equal length informs us about the limits of valid conclusions. Thus, for example, out of 500 stylemes in Plato[^10] observed in the last six dialogues (*Sophist*, *Statesman*, *Philebus*, *Timaeus*, *Critias*, *Laws*), we find close to the same number in samples of equal text in *Republic* and *Phaedrus* (which has generally been recognized as contemporaneous to *Republic*), namely:


* 101 stylemes equivalent to 192 units in *Republic*, 412b–471c (39 pp., ed. Didot; 63 pp., ed. Teubner).
* 99 stylemes equivalent to 184 units in *Republic*, 543a–592b (34 pp., ed. Didot; 55 pp., ed. Teubner).
* 119 stylemes equivalent to 220 units in *Phaedrus*, 227a–279c (39 pp., ed. Didot ; 68 pp., ed. Teubner).


Taking longer samples, the differences diminish. We find:


* 111 stylemes equivalent to 211 units in *Republic*, 368a–445e (53 pp., ed. Didot ; 87 pp., ed. Teubner).
* 124 stylemes equivalent to 233 units in *Republic*, 543a–621d (53 pp., ed. Didot ; 86 pp., ed. Teubner).
* 130 stylemes equivalent to 233 units in *Theaetetus*, 142a–210d (33 pp., ed. Didot ; 68 pp., ed. Teubner).


We see that three samples of texts, of which two are taken from the same work and a third from a work whose style is closely clustered with it (*Phaedrus* and *Theaetetus* have been recognized at the closest dialogues to *Republic* by all those who have studied Plato’s style), show almost the same resemblance with the last group of six dialogues, which proves that 500 stylemes are sufficient for conclusions about chronology, [p. 68] which amounts to samples of 34–53 pages in the Didot edition. At the same time, this example shows that the measure of text we use to measure the length of a sample is not unimportant. The last three samples, which are of equal length in the Didot edition, are 68–87 pages in the Teubner edition and 68–78 pages in the Estienne edition. If we compare these editions by counting the number of words on each page for different works, we shall find out that the pages of the Didot edition are much more equal between each other than are those in the other editions. This observation is very important, for all of our predecessors have made use of the pages of the Teubner or Estienne editions as the measure of text without noticing that these pages contain more or fewer words in different dialogues. In certain cases, this negligence prevented some interesting conclusions. Thus Lina,[^11] having studied the use of prepositions in all of Plato’s works, found no difference in frequency between dialogues so different in every respect as *Laches*, *Protagoras*, and *Statesman*, which, according to Lina, have the same frequency of 11 prepositions per page (Teubner edition). In reality, if the text is measured by pages in the Didot edition, 17 prepositions are found per page in *Protagoras*, 19.5 prepositions per page in *Laches*, and 21 prepositions per page in *Statesman*, a considerable difference that Lina did not notice and that confirms what we know moreover about the style of these dialogues. Taking care to only compare equal samples, we easily find the limits to the validity of our stylometric law for each number of compared stylemes. If we observe at 500 stylemes that texts belonging to the same period show an almost equal resemblance with a given standard, we can also easily convince ourselves that all cases where the relative order of two dialogues [p. 69] or of two parts of just one dialogue is known, the one that was written later has a greater resemblance to the last group. The following examples demonstrate this clearly:

![Table Page 74]

[TO BE CONTINUED …]

```{r}

table.p74.df <- read.csv(file = "/files/Lutoslawski.Principes.74.csv")

mean.v <- c(-1,-.5,0,.5,1)
colors <- c("red", "blue", "darkgreen", "gold", "purple")
plot(dnorm(seq(-4, 4, length=100), mean = mean.v[5]), lwd=2, col=colors[5], type="l", xaxt='n', yaxt='n',ann=FALSE)
for (i in 1:4){
  lines(dnorm(seq(-4, 4, length=100), mean = mean.v[i]), lwd=2, col=colors[i], type="l")
}
```

[^1]: Summary of a talk given to the *Académie des Inscriptions et Belles-Lettres* at the 18 June 1897 session. [TR: It was a Friday.]

[^2]: TR: I use they as a third-person singular pronoun.

[^3]: For evidence for this claim, see pp. 35–63, 241, 351–357, and 386–391 of W. Lutoslawski, The origin and growth of [*Plato’s Logic*](https://archive.org/details/origingrowthofpl00lutoiala/), London, 1897.

[^4]: *The Sophistes and Politicus of Plato, with a revised text and English notes* by the Rev. Lewis Campbell, Oxford, 1867. The importance of this work as containing a new method to study Plato’s style was first recognized in Poland in a work published in the *Mémoires de l'Académie des sciences de Cracovie*, vol. XXVI, p. 31-195 : “Ο pierwszych trzech tetralogiach dziel Platona,” which was summarized in *Archiv fur Geschichte der Philosophie*, vol. IX, pp. 67-114 (October 1895) : *Ueber Echtheit Reihenfolge und logische Theorien von Plato's drei ersten Tetralogien* and in the *Bulletin de l'Académie des sciences de Cracovie* October 1895, pp. 268–277.

[^5]: See pp. 416–471 of W. Lutoslawski, *The origin and growth of Plato's Logic*. For sake of brevity, this work will be cited below as *Plato's Logic*.

[^6]: For the enumeration and classification of these words, see pp. 88–99 of *Plato’s Logic*.

[^7]: Dittenberger, *Sprachliche Kriterien fur die Chronologie der platonischen Dialoge*, in *Hermes*, vol. XV, p. 321. Berlin, 1881.

[^8]: An analysis of the most important studies of this kind can be found in the essay *Sur une nouvelle méthode pour déterminer la chronologie des dialogues de Platon*, read on 16 May 1896 [TR: a Saturday] to the *Académie des sciences morales* [*et politiques*] and published in vol. CXLVI, n° 7 of the *Compte rendu* of this academy [[pp. 114–33; responses 133–35](https://gallica.bnf.fr/ark:/12148/bpt6k2992435/f960.item)]. Forty-five publications of Plato’s style are summarized in *Plato’s Logic*, pp. 74–140.

[^9]: See pp. 130 and 141 of *Plato's Logic*.

[^10]: The enumeration and discussion of these 500 stulemes gathered by twenty different authors at pp. 76–79, 85–88, 93–97, 100–104, 106–111, 115–133, and 137–139 of *Plato’s Logic*, and at pp 176–198 of vol. CX of the *Zeitschrift für Philosophie und philosophische Kritik*, in the September 1897 installment. See also the article [*Stylometrisches*](https://books.google.com/books?id=itJMAAAAMAAJ&q=Stylometrisches&dq=Stylometrisches&hl=en&sa=X&ved=0ahUKEwiK06KD2ZbeAhXpYt8KHcKfAJEQ6AEINzAC) in the CXIIth volume of the same *Zeitschrift*.

[^11]: T. Lina, *De praepositionum usu platonico*. Marpurgi, 1889. The numbers given by Lina for the frequency of the use of πέρι following the genitive are in disagreement with those given by M. Baron.


[Table Page 74]: /files/Lutoslawski.Principes.74.png